platform :ios, '9.0'

target 'MarvelCharacterList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'CryptoSwift'
  pod 'SwiftyJSON'

  target 'MarvelCharacterListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelCharacterListUITests' do
    # Pods for testing
  end

end
